---
- hosts: "agent"
  vars:
    ansible_become: yes
    ansible_become_user: "root"
    ansible_become_password: "{{ root-password }}"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  roles:
    - splunk-forwarder
